name: uniswap_sdk_dart
description: 4Swap API for Dart/Flutter.
version: 0.1.0
homepage: https://github.com/MixinNetwork/uniswap_sdk_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  dart_jsonwebtoken: ^2.6.2
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  test: ^1.22.1
  very_good_analysis: ^3.1.0

