name: uniswap_sdk_dart
description: 4Swap API for Dart/Flutter.
version: 0.1.0
homepage: https://github.com/MixinNetwork/uniswap_sdk_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  equatable: ^2.0.3
  json_annotation: ^4.7.0
  dart_jsonwebtoken: ^2.6.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  test: ^1.17.9
  very_good_analysis: ^3.0.1

